### ISSUE TITLE
Calendar is missing on plenary meeting page

### ISSUE THREAD

**Issue by LoganDupont** [laurensdeb/Federal-Parliament-Visualisations#5]
When navigating to https://parlement-in-data.thundr.be/meeting.html?session=55 we would normally see a calendar with the plenary meetings. Currently nothing is shown.

**Comment by ndossche** [comment]
Looks like vega updated and is now throwing "Unrecognized scheme name: gray_0_then_blues", will look at this tomorrow.

**Comment by LoganDupont** [comment]
Okay, thank you for the quick response!

**Comment by ndossche** [comment]
Ah oops I forgot to reply on this.
Anyway for future readers of this issue: this is solved right now.
